fix yaml

diff --git a/.github/workflows/fetch-data.yml b/.github/workflows/fetch-data.yml
--- a/.github/workflows/fetch-data.yml
+++ b/.github/workflows/fetch-data.yml
@@ -48,4 +48,24 @@ jobs:
 
       - name: Extract reportData.json
         run: |
-          if [ -f "reportData/reportData.js
+          if [ -f "reportData/reportData.json" ]; then
+            mv reportData/reportData.json .
+          else
+            echo "{}" > reportData.json  # Creates an empty JSON if missing
+          fi
+
+      - name: Build CLI
+        run: dotnet build --configuration Release RedditPing.CLI/RedditPing.CLI.csproj || exit 1
+
+      - name: Run CLI subreddit fetch
+        run: dotnet run --project RedditPing.CLI -- subreddit list -search-type 0 -limit 3 || exit 1
+
+      - name: Run CLI post fetch
+        run: dotnet run --project RedditPing.CLI -- post add -search-type 0 -limit 5 || exit 1
+
+      # Save updated reportData.json to cache
+      - name: Save reportData.json to cache
+        uses: actions/cache@v3
+        with:
+          path: reportData.json
+          key: report-data
